{% set name = "pytest-localstack" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 44ee795ff162085b6f5c51abcdb40687b36804a9ca10043629e3358343059ca3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - botocore >=1.4.31,!=1.4.45
    - contextlib2
    - docker-py
    - mock
    - pluggy >=0.6.0
    - pytest >=3.3.0
    - python
    - six

test:
  imports:
    - pytest_localstack
    - pytest_localstack.contrib

about:
  home: https://github.com/mintel/pytest-localstack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytest plugin for AWS integration tests
  doc_url: https://pypi.org/project/pytest-localstack/
  dev_url: https://github.com/mintel/pytest-localstack

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
    - rluria14
